apollo:
  bootstrap:
    enabled: true
    namespaces: application,authorization,web-client
  meta: http://localhost:8080

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.ghrk.paramgovernance.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  config:
    classpath:  ./logback-spring.xml  #日志相对路径
  #level:
    #root: info #日志级别 root表示所有包，也可以单独配置具体包 fatal>error>warn>info>debug>trace>off


server:
  port: 8081

dubbo:
  provider:
    timeout: 3000
    validation: true
    filter: -exception,-validation,dubboExceptionFilter,customValidationFilter
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://localhost:2181
  application:
    name: provider
    qos-enable: true # 是否开启QOS
    qos-port: 22222 # QOS端口默认端口
    qos-accept-foreign-ip: false # 是否允许QOS请求
    serialize-check-status: DISABLE
    check-serializable: false

#logging:
#  level:
##    com.ghrk.provider.dao: debug
#    com.baomidou.mybatisplus: debug
